version: "2"
linters:
  enable:
    - dupl
    - gochecknoinits
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - goconst
  settings:
     staticcheck:
       checks: ["all", "-ST1005"]
     goconst:
       min-len: 2
       min-occurrences: 2
     gocritic:
       disabled-checks:
         - wrapperFunc
         - hugeParam
         - rangeValCopy
         - singleCaseSwitch
         - ifElseChain
       enabled-tags:
         - performance
         - style
         - experimental
     govet:
       enable:
         - shadow
     lll:
       line-length: 140
     misspell:
       locale: US
     revive:
       rules:
         - name: package-comments
           disabled: true
formatters:
  enable:
    - gci
    - gofumpt
